authorName: default
experimentName: cifar10
trialConcurrency: 2
maxExecDuration: 10h
maxTrialNum: 1000
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
trial:
  command: python main.py
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: True
  gpuIndices: '0'
  maxTrialNumPerGpu: 2
assessor:
    builtinAssessorName: Medianstop
    classArgs:
      optimize_mode: maximize
      start_step: 5
